FROM python:3.12-slim

WORKDIR /srv

COPY app/requirements-api.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY app /srv/app

CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000"]
