PROBLEM = {
    "slug": "snake",
    "title": "Snake (Interactive)",
    "statement": "Write a bot to play Snake on a 20x20 map. You interact via stdio.",
    "input_format": "20x20 grid mapping, followed by N on the 21st line. Next lines indicate F.",
    "output_format": "W/A/S/D and your score.",
    "sample_input": "",
    "sample_output": "",
    "time_limit_ms": 2000,
    "memory_limit_mb": 128,
    "supported_languages": ["c", "cpp17"],
    "tests": [
        {"n": 1, "seed": 101},
        {"n": 2, "seed": 102},
        {"n": 4, "seed": 103},
        {"n": 8, "seed": 104},
        {"n": 16, "seed": 105},
        {"n": 32, "seed": 106},
        {"n": 64, "seed": 107},
        {"n": 128, "seed": 108},
        {"n": 256, "seed": 109},
        {"n": 512, "seed": 110},
    ],
}
